// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9P9GutzH_4gmZ-4XQeB053lXQNvBnd7o',
    appId: '1:329333032806:web:ee92e156b4e009f6636aa7',
    messagingSenderId: '329333032806',
    projectId: 'ghar-sathi',
    authDomain: 'ghar-sathi.firebaseapp.com',
    storageBucket: 'ghar-sathi.firebasestorage.app',
    measurementId: 'G-1LYMW4L279',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Kzbx1w8w8rPRBvq-cBDZ1Pk3NTvTJ0I',
    appId: '1:329333032806:android:2d7dddafcab9f277636aa7',
    messagingSenderId: '329333032806',
    projectId: 'ghar-sathi',
    storageBucket: 'ghar-sathi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgmGJsHWHEKvcxjZ_Hoo-PEBKkJLiLLxQ',
    appId: '1:329333032806:ios:b556d12edf983f2d636aa7',
    messagingSenderId: '329333032806',
    projectId: 'ghar-sathi',
    storageBucket: 'ghar-sathi.firebasestorage.app',
    iosBundleId: 'com.example.ghar_sathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgmGJsHWHEKvcxjZ_Hoo-PEBKkJLiLLxQ',
    appId: '1:329333032806:ios:b556d12edf983f2d636aa7',
    messagingSenderId: '329333032806',
    projectId: 'ghar-sathi',
    storageBucket: 'ghar-sathi.firebasestorage.app',
    iosBundleId: 'com.example.ghar_sathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9P9GutzH_4gmZ-4XQeB053lXQNvBnd7o',
    appId: '1:329333032806:web:379e0c1efe0caf43636aa7',
    messagingSenderId: '329333032806',
    projectId: 'ghar-sathi',
    authDomain: 'ghar-sathi.firebaseapp.com',
    storageBucket: 'ghar-sathi.firebasestorage.app',
    measurementId: 'G-YV81GR1X7D',
  );
}
